name: rachelling
favicon: null
layout_spectrum: 0.6334907114505768
typography_spectrum: 0.86644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ca8a8b'
    - '#eed6bc'
    - '#51282e'
    - '#844349'
    - '#7d6f34'
  brandStrength: 0.731739736860618
  lightness: 0.4172307460103184
  saturation: 0.697201797971502
  rhythmicContrast: 0.4384187099058181
purpose: []
